services:
  app:
    image: $APP_IMAGE
    hostname: "$APP_NAME.$BASE_DOMAIN"
    working_dir: /app
    # cosmtrek/air entrypoint is /go/bin/air
    command: ["-c", ".air.toml"]
    environment:
      APP_PORT: "$APP_PORT"
      VIRTUAL_HOST: "$APP_NAME.$BASE_DOMAIN"
      VIRTUAL_PORT: "$APP_PORT"
      air_wd: /app
      HOME: /tmp/home
      GOPATH: /tmp/home/go
      GOCACHE: /tmp/home/go-cache
      GOMODCACHE: /tmp/home/go-mod
    volumes:
      - "$SVC_PATH:/app"
      - "$HOME_PATH:/tmp/home"
    networks:
      - dev

networks:
  dev:
    external: true
    name: $NETWORK
