#!/bin/bash

umask 0000

cd /var/www

if [ -e "container.env" ]; then
    variables=$(sed 's/^#.*//' "container.env")
    if [ "$variables" != "" ]; then
        export $variables
    fi
fi

if [ ! -e /var/www/storage/ensi ] && [ -e /var/data ]; then
    ln -s /var/data /var/www/storage/ensi
fi

if [ ! -L /var/www/public/storage ]; then
    if [ -e vendor ]; then
        php artisan storage:link
    fi
fi

if [ "$XDEBUG_ENABLED" == "yes" ]; then
    {
        echo "xdebug.mode=off"
        echo "xdebug.start_with_request=yes"
        echo "xdebug.client_host=host.docker.internal"
        echo "xdebug.client_port=${XDEBUG_CLIENT_PORT}"
        echo "max_execution_time=3600"
    } >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    XDEBUG_MODE=debug php-fpm -R
else
    php-fpm -R
fi